version: '3.8'

# Services
services:

  # Nginx Service
  nginx:
<<<<<<< HEAD
    image: nginx:1.21-alpine
=======
    image: nginx:1.21
>>>>>>> 10a5af5 (Basic LEMP stack created)
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
<<<<<<< HEAD
      - phpmyadmindata:/var/www/phpmyadmin
    depends_on:
      - php
      - phpmyadmin
=======
    depends_on:
      - php
>>>>>>> 10a5af5 (Basic LEMP stack created)

  # PHP Service
  php:
    build: ./.docker/php
    working_dir: /var/www/php
    volumes:
      - ./src:/var/www/php
    depends_on:
      mysql:
        condition: service_healthy

  # MySQL Service
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: pfs
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

  # PhpMyAdmin Service
  phpmyadmin:
<<<<<<< HEAD
    image: phpmyadmin/phpmyadmin:5-fpm-alpine
    environment:
      PMA_HOST: mysql
    volumes:
      - phpmyadmindata:/var/www/html
=======
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
>>>>>>> 10a5af5 (Basic LEMP stack created)
    depends_on:
      mysql:
        condition: service_healthy

# Volumes
volumes:

<<<<<<< HEAD
  mysqldata:

  phpmyadmindata:
=======
  mysqldata:
>>>>>>> 10a5af5 (Basic LEMP stack created)
